In [1]:
# Ejercicio 1: Crear un array de 10 elementos con ceros.
import numpy as np

array = np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# Ejercicio 2: Genera un array con los números del 1 al 20.
import numpy as np

array = np.arange(1, 21)
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [5]:
# Ejercicio 3: Crea un array con los números pares del 2 al 50.
import numpy as np

array = np.arange(2, 51, 2)
print(array)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [7]:
# Ejercicio 5: Crea una matriz de 4x4 con valores aleatorios entre 0 y 1.
import numpy as np

matriz = np.random.rand(4, 4)
print(matriz)

[[0.71518975 0.09501812 0.63784503 0.02726227]
 [0.43682711 0.65432293 0.96045526 0.32192954]
 [0.95414425 0.34737271 0.01539162 0.16006571]
 [0.02758108 0.57503124 0.3829802  0.25896455]]


In [9]:
# Ejercicio 6: Realiza la suma elemento a elemento de los arrays a=[1,2,3], b=[4,5,6].
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

suma = a + b
print(suma)

[5 7 9]


In [11]:
# Ejercicio 7: Multiplica dos matrices 3x3 de enteros aleatorios entre 1 y 10.
import numpy as np

# Crear matrices 3x3 con enteros aleatorios entre 1 y 10
A = np.random.randint(1, 11, (3, 3))
B = np.random.randint(1, 11, (3, 3))

# Multiplicación matricial
resultado = np.dot(A, B)   # también podés usar A @ B

print("Matriz A:\n", A)
print("Matriz B:\n", B)
print("Resultado:\n", resultado)

Matriz A:
 [[ 8  5  8]
 [ 6  9 10]
 [10  3  8]]
Matriz B:
 [[ 7 10  7]
 [ 2  6 10]
 [ 7  2  1]]
Resultado:
 [[122 126 114]
 [130 134 142]
 [132 134 108]]


In [13]:
# Ejercicio 8: Crea un array de 15 valores aleatorios entre 1 y 100 e imprime su máximo, mínimo y promedio.
import numpy as np

# Crear array
array = np.random.randint(1, 101, 15)

# Calcular estadísticas
maximo = np.max(array)
minimo = np.min(array)
promedio = np.mean(array)

print("Array:", array)
print("Máximo:", maximo)
print("Mínimo:", minimo)
print("Promedio:", promedio)

Array: [ 8 41 20 98 72 53 82 62 70 32 85 82 16 30 75]
Máximo: 98
Mínimo: 8
Promedio: 55.06666666666667


In [15]:
# Ejercicio 9: Genera una matriz 5x5 con valores del 1 al 25 y extrae su diagonal.
import numpy as np

# Crear matriz 5x5 con valores del 1 al 25
matriz = np.arange(1, 26).reshape(5, 5)

# Extraer diagonal
diagonal = np.diag(matriz)

print("Matriz:\n", matriz)
print("Diagonal:", diagonal)

Matriz:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Diagonal: [ 1  7 13 19 25]


In [17]:
# Ejercicio 10 : Dada una matriz 5x5 de enteros aleatorios entre 1 y 20, calcula la suma de cada fila y columna
import numpy as np

# Crear matriz 5x5 con enteros aleatorios entre 1 y 20
matriz = np.random.randint(1, 21, (5, 5))

# Suma por filas (axis=1)
suma_filas = np.sum(matriz, axis=1)

# Suma por columnas (axis=0)
suma_columnas = np.sum(matriz, axis=0)

print("Matriz:\n", matriz)
print("Suma de filas:", suma_filas)
print("Suma de columnas:", suma_columnas)

Matriz:
 [[13  1  7  5  4]
 [ 1 20 17 18 17]
 [ 7  9  4 19 15]
 [ 2  7  1  6  9]
 [ 7 19 16  1 12]]
Suma de filas: [30 73 54 25 55]
Suma de columnas: [30 56 45 49 57]
